### ISSUE TITLE
Install module error on default Blender 3.5 install

### ISSUE THREAD

**Issue by azcoffeehabit** [hc-psy/blender-gpt#6]
Hi,  I have an error when trying to enable the blender GPT add-on.    This is a default install of Blender 3.5.   Python console works.
Thank you for the cool tool!

System:
Windows 11 x64
Blender 3.5
Python 3.10

Steps:
1. Download .zip file from github
2. Install Add In
3. Enable Add in

Error below will appear.  Maybe i am missing a pre-requisite which is not in the readme?

Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-gpt-main\gpt_pkg.py", line 44, in installModule
    subprocess.call([python_exe, "import ", packageName])
UnboundLocalError: local variable 'python_exe' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-gpt-main\__init__.py", line 3, in <module>
    from .gpt_pkg import *
  File "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-gpt-main\gpt_pkg.py", line 55, in <module>
    installModule('openai')
  File "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-gpt-main\gpt_pkg.py", line 46, in installModule
    python_exe = python_exec()
  File "C:\Users\XXXXX\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-gpt-main\gpt_pkg.py", line 23, in python_exec
    return os.path.join(sys.prefix, 'bin', 'python.exe')
UnboundLocalError: local variable 'sys' referenced before assignment

**Comment by ryvn-dev** [comment]
Thank you for reporting the installation issue with our module. We've recently updated our add-on to version v0.0.2, which includes fixes that might resolve this problem. Could you download the latest version from our release page and try installing it again?

If you encounter any further issues, please feel free to let us know!

Cheers! 🌟
