### ISSUE TITLE
Install module error on Blender 3.6.2

### ISSUE THREAD

**Issue by Bisnis3d** [hc-psy/blender-gpt#8]
Windows 10
Blender 3.6.2
Python 3.10

I can't activate it, because this error.
--------------------------------------------
Traceback (most recent call last):
  File "C:\Users\XxXxX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-gpt-main\gpt_pkg.py", line 44, in installModule
    subprocess.call([python_exe, "import ", packageName])
UnboundLocalError: local variable 'python_exe' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\XxXxX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-gpt-main\__init__.py", line 3, in <module>
    from .gpt_pkg import *
  File "C:\Users\XxXxX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-gpt-main\gpt_pkg.py", line 55, in <module>
    installModule('openai')
  File "C:\Users\XxXxX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-gpt-main\gpt_pkg.py", line 46, in installModule
    python_exe = python_exec()
  File "C:\Users\XxXxX\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-gpt-main\gpt_pkg.py", line 23, in python_exec
    return os.path.join(sys.prefix, 'bin', 'python.exe')
UnboundLocalError: local variable 'sys' referenced before assignment

**Comment by ryvn-dev** [comment]
Thanks for pointing out the module installation issue. We've made some updates in v0.0.2 that should address this. Please head over to the release page and give it another try with the latest version.

If you're still running into problems, don't hesitate to reach out!

Cheers! 🌟
